### ISSUE TITLE
 TypeError: Cannot set property 'family' of undefined Still Present

### ISSUE THREAD

**Issue by madskunker** [iarna/rtf-parser#3]
TypeError: Cannot set property 'family' of undefined
5|basin    |     at RTFInterpreter.ctrl$fbidi (/usr/local/TP/tpmicroservice/node_modules/rtf-parser/rtf-interpreter.js:240:35)
5|basin    |     at RTFInterpreter.cmd$controlWord (/usr/local/TP/tpmicroservice/node_modules/rtf-parser/rtf-interpreter.js:98:19)
5|basin    |     at RTFInterpreter._write (/usr/local/TP/tpmicroservice/node_modules/rtf-parser/rtf-interpreter.js:59:19)
5|basin    |     at doWrite (/usr/local/TP/tpmicroservice/node_modules/readable-stream/lib/_stream_writable.js:347:64)
5|basin    |     at writeOrBuffer (/usr/local/TP/tpmicroservice/node_modules/readable-stream/lib/_stream_writable.js:336:5)
5|basin    |     at RTFInterpreter.Writable.write (/usr/local/TP/tpmicroservice/node_modules/readable-stream/lib/_stream_writable.js:274:11)
5|basin    |     at RTFParser.ondata (/usr/local/TP/tpmicroservice/node_modules/readable-stream/lib/_stream_readable.js:546:20)
5|basin    |     at emitOne (events.js:96:13)
5|basin    |     at RTFParser.emit (events.js:188:7)
5|basin    |     at readableAddChunk (/usr/local/TP/tpmicroservice/node_modules/readable-stream/lib/_stream_readable.js:217:18)

**Comment by iarna** [comment]
Hey, thanks for reporting this, it should be fixed in 1.5

**Comment by andystevensname** [comment]
I'm still receiving this error in 1.0.5. Node v7.6.0, npm v5.4.1

```
TypeError: Cannot set property 'family' of undefined
    at RTFInterpreter.ctrl$froman (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/rtf-parser/rtf-interpreter.js:222:35)
    at RTFInterpreter.cmd$controlWord (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/rtf-parser/rtf-interpreter.js:98:19)
    at RTFInterpreter._write (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/rtf-parser/rtf-interpreter.js:59:19)
    at doWrite (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at RTFInterpreter.Writable.write (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at RTFParser.ondata (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:96:13)
    at RTFParser.emit (events.js:189:7)
    at addChunk (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/readable-stream/lib/_stream_readable.js:284:12)
    at readableAddChunk (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/readable-stream/lib/_stream_readable.js:271:11)
    at RTFParser.Readable.push (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/readable-stream/lib/_stream_readable.js:238:10)
    at RTFParser.Transform.push (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/readable-stream/lib/_stream_transform.js:146:32)
    at RTFParser.emitControlWord (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/rtf-parser/rtf-parser.js:136:12)
    at RTFParser.parseControlWord (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/rtf-parser/rtf-parser.js:109:12)
    at RTFParser._transform (/Users/ovenbird/Documents/Projects/AStreamForVoices/astreamforvoices/node_modules/rtf-parser/rtf-parser.js:26:12)
```

**Comment by iarna** [comment]
@andystevensname Can you upload example RTF somewhere that's causing this crash?

**Comment by iarna** [comment]
oh, ok, I think I see where this is going wrong… we may be seeing font declarations when not inside a font table. I _think_ that's technically invalid but it's honestly hard to tell from the spec and it still shouldn't crash…

**Comment by andystevensname** [comment]
This is an RTF string of the words 'Test Document' that is generated by exporting from the Google Drive API:
```
{\rtf1\ansi\ansicpg1252\uc0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deff0\adeff0{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f1\froman\fcharset2\fprq2{\*\panose 05050102010706020507}Symbol;}{\f2\fswiss\fcharset0\fprq2{\*\panose 020b0604020202020204}Arial;}{\f3\fnil\fcharset0 Trebuchet MS;}}{ \colortbl;\red0\green0\blue0;\red102\green102\blue102;}{\stylesheet{\s0\snext0\sqformat\spriority0\fi0\sb0\sa0\aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab0\ai0\af0\afs24\ltrch\b0\i0\fs24\f0\strike0\ulnone\cf1 Normal;}{\s1\sbasedon0\snext0\styrsid15694742 \sqformat\spriority0\fi0\sb0\sa0\aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li360\lin360\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab\ai0\af0\afs24\ltrch\b\i0\fs24\f0\strike0\ul\cf1 heading 1;}{\s2\sbasedon0\snext0\styrsid15694742\sqformat\spriority0\keep\keepn\fi0\sb200\sa0 \aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab\ai0\af3\afs26\ltrch\b\i0\fs26\loch\af3\dbch\af3\hich\f3\strike0\ulnone\cf1 heading 2;}{\s3\sbasedon0\snext0\styrsid15694742\sqformat\spriority0\keep\keepn\fi0\sb160\sa0 \aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab\ai0\af3\afs24\ltrch\b\i0\fs24\loch\af3\dbch\af3\hich\f3\strike0\ulnone\cf2 heading 3;}{\s4\sbasedon0\snext0\styrsid15694742\sqformat\spriority0\keep\keepn\fi0\sb160\sa0 \aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab0\ai0\af3\afs22\ltrch\b0\i0\fs22\loch\af3\dbch\af3\hich\f3\strike0\ul\cf2 heading 4;}{\s5\sbasedon0\snext0\styrsid15694742\sqformat\spriority0\keep\keepn\fi0\sb160\sa0 \aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab0\ai0\af3\afs22\ltrch\b0\i0\fs22\loch\af3\dbch\af3\hich\f3\strike0\ulnone\cf2 heading 5;}{\s6\sbasedon0\snext0\styrsid15694742\sqformat\spriority0\keep\keepn\fi0\sb160\sa0 \aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab0\ai\af3\afs22\ltrch\b0\i\fs22\loch\af3\dbch\af3\hich\f3\strike0\ulnone\cf2 heading 6;}{\*\cs10\additive\ssemihidden\spriority0 Default Paragraph Font;}{\s15\sbasedon0\snext15\styrsid15694742 \sqformat\spriority0\keep\keepn\fi0\sb0\sa0\aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab0\ai0\af3\afs42\ltrch\b0\i0\fs42\loch\af3\dbch\af3\hich\f3\strike0\ulnone\cf1 Title;}{\s16\sbasedon0\snext16\styrsid15694742 \sqformat\spriority0\keep\keepn\fi0\sb0\sa200\aspalpha\aspnum\adjustright\nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab0\ai\af3\afs26\ltrch\b0\i\fs26\loch\af3\dbch\af3\hich\f3\strike0\ulnone\cf2 Subtitle;}}{\*\rsidtbl\rsid10976062}{\*\generator Aspose.Words for Java 13.10.0.0;}{\info\version1\edmins0\nofpages1\nofwords0\nofchars0\nofcharsws0}{\mmathPr\mbrkBin0\mbrkBinSub0\mdefJc1\mdispDef1\minterSp0\mintLim0\mintraSp0\mlMargin0\mmathFont0\mnaryLim1\mpostSp0\mpreSp0\mrMargin0\msmallFrac0\mwrapIndent1440\mwrapRight0} \deflang1033\deflangfe2052\adeflang1025\jexpand\showxmlerrors1\validatexml1{\*\wgrffmtfilter 013f}\viewkind1\viewscale100\fet0\ftnbj\aenddoc\ftnrstcont\aftnrstcont\ftnnar\aftnnrlc\widowctrl\nospaceforul\nolnhtadjtbl\alntblind\lyttblrtgr\dntblnsbdb\noxlattoyen \wrppunct\nobrkwrptbl\expshrtn\snaptogridincell\asianbrkrule\htmautsp\noultrlspc\useltbaln\splytwnine\ftnlytwnine\lytcalctblwd\allowfieldendsel\lnbrkrule\nouicompat\nofeaturethrottle1\formshade\nojkernpunct\dghspace180\dgvspace180\dghorigin1800\dgvorigin1440\dghshow1\dgvshow1 \dgmargin\pgbrdrhead\pgbrdrfoot\sectd\sectlinegrid360\pgwsxn12240\pghsxn15840\marglsxn1440\margrsxn1440\margtsxn1440\margbsxn1440\guttersxn0\headery708\footery708\colsx708\ltrsect\pard\plain\itap0\s0\ilvl0\fi0\sb0\sa0\aspalpha\aspnum\adjustright\brdrt\brdrl\brdrb\brdrr\brdrbtw\brdrbar \nowidctlpar\ltrpar\li0\lin0\ri0\rin0\ql\faauto\sl480\slmult1\rtlch\ab0\ai0\af0\afs24\ltrch\b0\i0\fs24\f0\strike0\ulnone\cf1{\rtlch\ab0\ai0\af0\afs24\ltrch\b0\i0\fs24\f0\strike0\ulnone\cf1 Test}{\rtlch\ab0\ai0\af0\afs24\ltrch\b0\i0\fs24\f0\strike0\ulnone\cf1 }{ \rtlch\ab0\ai0\af0\afs24\ltrch\b0\i0\fs24\f0\strike0\ulnone\cf1 Document}{\rtlch\ab0\ai0\af0\afs24\ltrch\b0\i0\fs24\f0\insrsid10976062\strike0\ulnone\cf1\par}{\*\latentstyles\lsdstimax267\lsdlockeddef0\lsdsemihiddendef0\lsdunhideuseddef0\lsdqformatdef0\lsdprioritydef0{\lsdlockedexcept\lsdqformat1 Normal;\lsdqformat1 heading 1;\lsdsemihidden1\lsdunhideused1\lsdqformat1 heading 2;\lsdsemihidden1\lsdunhideused1\lsdqformat1 heading 3 ;\lsdsemihidden1\lsdunhideused1\lsdqformat1 heading 4;\lsdsemihidden1\lsdunhideused1\lsdqformat1 heading 5;\lsdsemihidden1\lsdunhideused1\lsdqformat1 heading 6;\lsdsemihidden1\lsdunhideused1\lsdqformat1 heading 7;\lsdsemihidden1\lsdunhideused1\lsdqformat1 heading 8 ;\lsdsemihidden1\lsdunhideused1\lsdqformat1 heading 9;\lsdsemihidden1\lsdunhideused1\lsdqformat1 caption;\lsdqformat1 Title;\lsdqformat1 Subtitle;\lsdqformat1 Strong;\lsdqformat1 Emphasis;\lsdsemihidden1\lsdpriority99 Placeholder Text;\lsdqformat1\lsdpriority1 No Spacing ;\lsdpriority60 Light Shading;\lsdpriority61 Light List;\lsdpriority62 Light Grid;\lsdpriority63 Medium Shading 1;\lsdpriority64 Medium Shading 2;\lsdpriority65 Medium List 1;\lsdpriority66 Medium List 2;\lsdpriority67 Medium Grid 1;\lsdpriority68 Medium Grid 2 ;\lsdpriority69 Medium Grid 3;\lsdpriority70 Dark List;\lsdpriority71 Colorful Shading;\lsdpriority72 Colorful List;\lsdpriority73 Colorful Grid;\lsdpriority60 Light Shading Accent 1;\lsdpriority61 Light List Accent 1;\lsdpriority62 Light Grid Accent 1;\lsdpriority63 Medium Shading 1 Accent 1 ;\lsdpriority64 Medium Shading 2 Accent 1;\lsdpriority65 Medium List 1 Accent 1;\lsdsemihidden1\lsdpriority99 Revision;\lsdqformat1\lsdpriority34 List Paragraph;\lsdqformat1\lsdpriority29 Quote;\lsdqformat1\lsdpriority30 Intense Quote;\lsdpriority66 Medium List 2 Accent 1 ;\lsdpriority67 Medium Grid 1 Accent 1;\lsdpriority68 Medium Grid 2 Accent 1;\lsdpriority69 Medium Grid 3 Accent 1;\lsdpriority70 Dark List Accent 1;\lsdpriority71 Colorful Shading Accent 1;\lsdpriority72 Colorful List Accent 1;\lsdpriority73 Colorful Grid Accent 1 ;\lsdpriority60 Light Shading Accent 2;\lsdpriority61 Light List Accent 2;\lsdpriority62 Light Grid Accent 2;\lsdpriority63 Medium Shading 1 Accent 2;\lsdpriority64 Medium Shading 2 Accent 2;\lsdpriority65 Medium List 1 Accent 2;\lsdpriority66 Medium List 2 Accent 2 ;\lsdpriority67 Medium Grid 1 Accent 2;\lsdpriority68 Medium Grid 2 Accent 2;\lsdpriority69 Medium Grid 3 Accent 2;\lsdpriority70 Dark List Accent 2;\lsdpriority71 Colorful Shading Accent 2;\lsdpriority72 Colorful List Accent 2;\lsdpriority73 Colorful Grid Accent 2 ;\lsdpriority60 Light Shading Accent 3;\lsdpriority61 Light List Accent 3;\lsdpriority62 Light Grid Accent 3;\lsdpriority63 Medium Shading 1 Accent 3;\lsdpriority64 Medium Shading 2 Accent 3;\lsdpriority65 Medium List 1 Accent 3;\lsdpriority66 Medium List 2 Accent 3 ;\lsdpriority67 Medium Grid 1 Accent 3;\lsdpriority68 Medium Grid 2 Accent 3;\lsdpriority69 Medium Grid 3 Accent 3;\lsdpriority70 Dark List Accent 3;\lsdpriority71 Colorful Shading Accent 3;\lsdpriority72 Colorful List Accent 3;\lsdpriority73 Colorful Grid Accent 3 ;\lsdpriority60 Light Shading Accent 4;\lsdpriority61 Light List Accent 4;\lsdpriority62 Light Grid Accent 4;\lsdpriority63 Medium Shading 1 Accent 4;\lsdpriority64 Medium Shading 2 Accent 4;\lsdpriority65 Medium List 1 Accent 4;\lsdpriority66 Medium List 2 Accent 4 ;\lsdpriority67 Medium Grid 1 Accent 4;\lsdpriority68 Medium Grid 2 Accent 4;\lsdpriority69 Medium Grid 3 Accent 4;\lsdpriority70 Dark List Accent 4;\lsdpriority71 Colorful Shading Accent 4;\lsdpriority72 Colorful List Accent 4;\lsdpriority73 Colorful Grid Accent 4 ;\lsdpriority60 Light Shading Accent 5;\lsdpriority61 Light List Accent 5;\lsdpriority62 Light Grid Accent 5;\lsdpriority63 Medium Shading 1 Accent 5;\lsdpriority64 Medium Shading 2 Accent 5;\lsdpriority65 Medium List 1 Accent 5;\lsdpriority66 Medium List 2 Accent 5 ;\lsdpriority67 Medium Grid 1 Accent 5;\lsdpriority68 Medium Grid 2 Accent 5;\lsdpriority69 Medium Grid 3 Accent 5;\lsdpriority70 Dark List Accent 5;\lsdpriority71 Colorful Shading Accent 5;\lsdpriority72 Colorful List Accent 5;\lsdpriority73 Colorful Grid Accent 5 ;\lsdpriority60 Light Shading Accent 6;\lsdpriority61 Light List Accent 6;\lsdpriority62 Light Grid Accent 6;\lsdpriority63 Medium Shading 1 Accent 6;\lsdpriority64 Medium Shading 2 Accent 6;\lsdpriority65 Medium List 1 Accent 6;\lsdpriority66 Medium List 2 Accent 6 ;\lsdpriority67 Medium Grid 1 Accent 6;\lsdpriority68 Medium Grid 2 Accent 6;\lsdpriority69 Medium Grid 3 Accent 6;\lsdpriority70 Dark List Accent 6;\lsdpriority71 Colorful Shading Accent 6;\lsdpriority72 Colorful List Accent 6;\lsdpriority73 Colorful Grid Accent 6 ;\lsdqformat1\lsdpriority19 Subtle Emphasis;\lsdqformat1\lsdpriority21 Intense Emphasis;\lsdqformat1\lsdpriority31 Subtle Reference;\lsdqformat1\lsdpriority32 Intense Reference;\lsdqformat1\lsdpriority33 Book Title;\lsdsemihidden1\lsdunhideused1\lsdpriority37 Bibliography ;\lsdsemihidden1\lsdunhideused1\lsdqformat1\lsdpriority39 TOC Heading;}}}
```

**Comment by iarna** [comment]
TY that does it. I can guard all the font settings, though I'd like to figure out what I _should do_, my guess is that they're inside the style sheet declarations that I don't currently support. More concerning it seems that they're wrapping all their text in an RTF tag I didn't implement (`rtlch`).

**Comment by iarna** [comment]
Ah, ok, that's easy to handle: `\rtlch The character data following this control word is treated as a right-to-left run.`

**Comment by andystevensname** [comment]
That is strange that the right to left is a default tag, I only use a western keyboard and English language settings on Google, but I'm glad you were able to discern the issue. Thanks for taking a look at this!

**Comment by iarna** [comment]
I've just published 1.1.0, please give it a try =)

**Comment by andystevensname** [comment]
It works great 👍, thank you!

**Comment by iarna** [comment]
Awesome!
