### ISSUE TITLE
Signed integers in RTF files stopping interpretation

### ISSUE THREAD

**Issue by markgillnz** [iarna/rtf-parser#7]
Some RTF files have signed integers such as -3091. These are causing the parser to fall over with the error below
`TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1178:11)
    at Buffer.writeUInt16LE (buffer.js:1236:5)
    at RTFInterpreter.ctrl$u (/Users/markgi/spike-rtf-to-html/node_modules/rtf-parser/rtf-interpreter.js:158:13)
    at RTFInterpreter.cmd$controlWord (/Users/markgi/spike-rtf-to-html/node_modules/rtf-parser/rtf-interpreter.js:99:19)
    at RTFInterpreter._write (/Users/markgi/spike-rtf-to-html/node_modules/rtf-parser/rtf-interpreter.js:46:19)
    at doWrite (/Users/markgi/spike-rtf-to-html/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/markgi/spike-rtf-to-html/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at RTFInterpreter.Writable.write (/Users/markgi/spike-rtf-to-html/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at RTFParser.ondata (/Users/markgi/spike-rtf-to-html/node_modules/readable-stream/lib/_stream_readable.js:612:20)
    at emitOne (events.js:115:13)`

**Comment by markgillnz** [comment]
I have addressed this with PR #6

**Comment by iarna** [comment]
Fixed in 1.2.0!
